---
abstract: 'UUID based file storage'
author:
  - 'Guillermo Roditi (groditi) <groditi@cpan.org>'
build_requires:
  Directory::Scratch: 0
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cantella-Store-UUID
no_index:
  directory:
    - inc
    - t
requires:
  Class::MOP: 0
  Data::GUID: 0
  File::Copy: 0
  File::MimeInfo: 0.15
  JSON: 0
  Moose: 0
  MooseX::Types::Data::GUID: 0.001000
  MooseX::Types::Path::Class: 0.05
  Path::Class: 0.18
  Sub::Exporter: 0
  namespace::autoclean: 0.09
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/groditi/Cantella-Store-UUID
version: 0.003000
